let data = [
    {
        id: 1,
        title:'갠소',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 2,
        title:'모코블링',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 3,
        title:'에바주니',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 4,
        title:'Huit8',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 5,
        title:'코라오가닉스',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 6,
        title:'스킨그래머',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 7,
        title:'업타운홀릭',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 8,
        title:'업타운홀릭 리즈',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 9,
        title:'뮬리안',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','MAKESHOP','MOBILE'],
    },
    {
        id: 10,
        title:'공구우먼',
        contentTxt:'메이크샵 솔루션을 사용하여 제작된 PC,모바일 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPINGMALL','MAKESHOP','MOBILE'],
    },
    {
        id: 11,
        title:'레시펫',
        contentTxt:'프리미엄 반려동물 용품 반응형 쇼핑몰',
        contentImg:[],
        tags:['WEB','SHOPING MALL','RESPONSIVE'],
    },
    {
        id: 12,
        title:'애드플랫',
        contentTxt:'아파트 광고 전단광고 플랫폼',
        contentImg:[],
        tags:['WEB','RESPONSIVE'],
    },
    {
        id: 13,
        title:'알파박스',
        contentTxt:'공유창고 셀프 스토리지 서비스 웹',
        contentImg:[],
        tags:['WEB','RESPONSIVE'],
    },
    {
        id: 14,
        title:'골든펫',
        contentTxt:'프리미엄 반려견케어 서비스 웹',
        contentImg:[],
        tags:['WEB','RESPONSIVE'],
    },
    {
        id: 15,
        title:'미인하이',
        contentTxt:'피부 성형 시술 정보 웹/앱',
        contentImg:[],
        tags:['WEB','RESPONSIVE'],
    },
    {
        id: 16,
        title:'위로',
        contentTxt:'쉬운 PC/모바일 부고장 서비스',
        contentImg:[],
        tags:['WEB','RESPONSIVE','VUE','MOBILE'],
    },
    {
        id: 17,
        title:'캔고루',
        contentTxt:'전시,박람회 전문 플랫폼',
        contentImg:[],
        tags:['WEB'],
    },
    {
        id: 18,
        title:'우리아이들',
        contentTxt:'아이 성장 관찰기록 플랫폼',
        contentImg:[],
        tags:['WEB'],
    },
    {
        id: 19,
        title:'태하',
        contentTxt:'주식회사 태하 홈페이지',
        contentImg:[],
        tags:['WEB'],
    },
    {
        id: 20,
        title:'리치 렌터카',
        contentTxt:'렌터카 홈페이지',
        contentImg:[],
        tags:['WEB'],
    },
    {
        id: 21,
        title:'유전체데이터시각화 플랫폼',
        contentTxt:'유전체데이터시각화 플랫폼',
        contentImg:[],
        tags:['WEB','SOLUTION'],
    },
    {
        id: 22,
        title:'실시간음성인식 솔루션',
        contentTxt:'실시간음성인식 솔루션',
        contentImg:[],
        tags:['WEB','SOLUTION'],
    },
    {
        id: 23,
        title:'알밥',
        contentTxt:'비대면 결제 서비스',
        contentImg:[],
        tags:['WEB','MOBILE'],
    },
    {
        id: 24,
        title:'라이트닝 트래커',
        contentTxt:'낙뢰 예측/알림 앱',
        contentImg:[],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 25,
        title:'미인하이',
        contentTxt:'뷰티/메디컬 소셜 커머스',
        contentImg:[],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 26,
        title:'지금부터 금연',
        contentTxt:'금연 보조 앱',
        contentImg:[],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 27,
        title:'리뷰닥',
        contentTxt:'리얼한 후기, 쁘띠, 성형, 시술, 뷰티 정보 앱',
        contentImg:[],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 28,
        title:'고친',
        contentTxt:'대학 입시 멘토,멘티 연결 플랫폼',
        contentImg:[],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 29,
        title:'코인아일랜드',
        contentTxt:'글로벌 가상화폐 결제 플랫폼',
        contentImg:['01','02'],
        tags:['APP','HYBRID APP'],
    },
    {
        id: 30,
        title:'e트럭 플러스',
        contentTxt:'화물 배차 연결 플랫폼',
        contentImg:['01'],
        tags:['APP','HYBRID APP'],
    },
]
export default data;