name: GreatComapny deplay
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Auto build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production