name: GreatComapny deplay
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Auto build
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        node-version: [16.18.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env: 
          NODE_ENV: production
          
      - name: SSH deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_ID }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "build/*"
          strip_components: 1
          target: "/home/greatcompany/build"
