name: GreatComapny deplay
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Auto build
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        node-version: [16.18.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env: 
          NODE_ENV: production
